Добавляет решение задачи: "сервер наносит первый удар"
htmlacademy-nodejs/1202-buy-and-sell-3 pull request #5
Opened 2020-04-29 12:11 UTC by thedoctorde

2020-04-29 14:18 UTC, delagen requested changes

2020-04-29 14:18 UTC, Delagen commented on src/service/cli/server.js
> +          console.error(chalk.red(`Can't read data from file ${FILE_NAME}... Error: ${e}`));
Тут получится не только в случае отсутствия файла, но и в том случае, когда файл по каким то причинам недоступен

2020-04-29 14:18 UTC, Delagen commented on src/service/cli/server.js
> +        const result = JSON.parse(data);
В случае ошибки происходит продолжение выполнения, что влечет дополнительные ошибки в следствие попытки повторной отправки результата

2020-04-30 10:27 UTC, thedoctorde commented on src/service/cli/server.js
> +          console.error(chalk.red(`Can't read data from file ${FILE_NAME}... Error: ${e}`));
Исправил здесь https://github.com/htmlacademy-nodejs/1202-buy-and-sell-3/pull/5/commits/61e4a017acd152e6db06a9b1337d325009469913

2020-04-30 10:27 UTC, thedoctorde commented on src/service/cli/server.js
> +        const result = JSON.parse(data);
Исправил вот тут https://github.com/htmlacademy-nodejs/1202-buy-and-sell-3/pull/5/commits/61e4a017acd152e6db06a9b1337d325009469913

2020-05-02 10:55 UTC, merged